CREATE TABLE IF NOT EXISTS depenses(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    categorie VARCHAR(50) NOT NULL,
    depense INTEGER NOT NULL,
    dates VARCHAR(50) NOT NULL
)

CREATE TABLE IF NOT EXISTS recus(
    recu INTEGER NOT NULL
)